### ISSUE TITLE
https://www.planetcrust.com/what-does-apache-2-0-license-mean?utm_campaign=blog#:~:text=Furthermore%2C%20developers%20can%20then%20distribute,notices%20on%20all%20altered%20files.

### ISSUE THREAD

**Issue by BlackHC** [genedisco/genedisco#10]
https://www.planetcrust.com/what-does-apache-2-0-license-mean?utm_campaign=blog#:~:text=Furthermore%2C%20developers%20can%20then%20distribute,notices%20on%20all%20altered%20files.

Please attribute the changes to the source code in the file then. The copyright notice in the file is misleading.
You cannot add my notice to your notice and then slap a separate notice on top of the file that you took without alterations and not mention my copyright.

Also please acknowledge my citation request for BatchBALD.

Thanks,
Andreas

_Originally posted by @BlackHC in https://github.com/genedisco/genedisco/issues/9#issuecomment-1546657103_

**Comment by genedisco** [comment]
Thanks. We added a comment to the file that should help avoid any potential misunderstandings.

For any other requests, please reach out to an author directly.
