### ISSUE TITLE
genedisco dependency incompatibility with evalai

### ISSUE THREAD

**Issue by jgamper** [genedisco/genedisco#2]
Hey, interesting challenge. Perhaps you could setup your repos with poetry, to ensure complete reproducibility? 

When installing your repository using [poetry](https://python-poetry.org/) alongside evalai package, poetry package management points to incompatibility:

```
Because no versions of evalai match >1.3.14,<2.0.0
and evalai (1.3.14) depends on requests (2.25.1), evalai (>=1.3.14,<2.0.0) requires requests (2.25.1).
And because genedisco (rev master) depends on requests (>=2.26.0), evalai (>=1.3.14,<2.0.0) is incompatible with 
genedisco (rev master). So, because genedisco-challenge depends on both genedisco (branch master) 
and evalai (^1.3.14), version solving failed.
```

**Comment by genedisco** [comment]
Thank you, Jev. The `genedisco` repo was not tested with `poetry` - we would recommend the use of `virtualenv` and `PIP` as an alternative package management solution.

Many thanks!
