### ISSUE TITLE
Acknowledgement form and Notice 

### ISSUE THREAD

**Issue by BlackHC** [genedisco/genedisco#9]
Hello again,

I've replied to the original issue that you closed and I'm not sure if you receive notifications for that.

1. Could you please use my full name: Andreas Kirsch in the acknowledgments in the form:

> consistent_mc_dropout.py was taken from https://github.com/BlackHC/batchbald_redux by Andreas Kirsch. Please cite the BatchBALD paper if you use consistent MC dropout (https://arxiv.org/abs/1906.08158).

2. According to https://www.apache.org/licenses/LICENSE-2.0#apply, a NOTICE text file is not necessary. It is only required for ASF projects.

Regardless, I've added a NOTICE now: https://github.com/BlackHC/batchbald_redux/blob/master/NOTICE

Either way, please remove your own copyright notice from that file in your repository, as it is wrong.

Thanks so much for the quick reply.

Best wishes,
 Andreas

_Originally posted by @BlackHC in https://github.com/genedisco/genedisco/issues/8#issuecomment-1542514622_

**Comment by genedisco** [comment]
Hi @BlackHC 

Thank you for amending your repository to include one of the mechanisms for attribution offered by the Apache license. We have added the NOTICE file to the repository to accommodate your request.

> Either way, please remove your own copyright notice from that file in your repository, as it is wrong.

It is our institutional policy to mark every file distributed with a licensing header as this is required for certain clauses of licenses to take effect (see below). Redistribution and relicensing is explicitly allowed under the Apache 2.0 license. 

PS: Your contribution to Open Source code is very much appreciated and most commendable indeed - however, it is important to configure your repository and license such that the stated conditions reflect your intended licensing conditions. Your original license formalises that you are happy without any attribution. There are two ways to attribute under Apache 2, 1) to include a license notice in each Source file that you wish to attribute (paragraph 4c) and/or 2) inclusion of a NOTICE text file (paragraph 4d) - you have not included either in your distributed Source work. Your institutional IP representative is likely able to help clarify the correct configuration of your distributions according to your intentions.

**Comment by BlackHC** [comment]
https://www.planetcrust.com/what-does-apache-2-0-license-mean?utm_campaign=blog#:~:text=Furthermore%2C%20developers%20can%20then%20distribute,notices%20on%20all%20altered%20files.

Please attribute the changes to the source code in the file then. The copyright notice in the file is misleading.
You cannot add my notice to your notice and then slap a separate notice on top of the file that you took without alterations and not mention my copyright.

Also please acknowledge my citation request for BatchBALD.

Thanks,
Andreas
